eyaya-4- Final project/DRK2/urls.py
from django.contrib import admin
from django.urls import path , include
from django.conf import settings
from django.conf.urls.static import static
from django.urls import include , path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('store.urls', namespace='store')),
    path('basket/',include('basket.urls', namespace='basket')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,document_root = settings.MEDIA_ROOT)

eyaya-4- Final project/basket/urls.py
from django.urls import path

from . import views

app_name = 'basket'
urlpatterns = [
    path('', views.basket_summary, name='basket_summary'),
    path('add/', views.basket_add, name='basket_add'),
]

eyaya-4- Final project/eyaya3 - Final project/DRK2/urls.py
from django.contrib import admin
from django.urls import path , include
from django.conf import settings
from django.conf.urls.static import static
from django.urls import include , path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('store.urls', namespace='store')),
    path('basket/',include('basket.urls', namespace='basket')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,document_root = settings.MEDIA_ROOT)

eyaya-4- Final project/eyaya3 - Final project/basket/urls.py
from django.urls import path

from . import views

app_name = 'basket'
urlpatterns = [
    path('', views.basket_summary, name='basket_summary'),
    path('add/', views.basket_add, name='basket_add'),
]

eyaya-4- Final project/eyaya3 - Final project/store/urls.py
from django.urls import path
from .import views



app_name ='store'

urlpatterns = [
    path ('', views.all_books , name='all_books'),
    path ('item/<slug:slug>/', views.book_details , name='book'),
    path('categories/<slug:slug>/', views.category_list, name='category_list'),


]

eyaya-4- Final project/store/urls.py
from django.urls import path
from .import views



app_name ='store'

urlpatterns = [
    path ('', views.all_books , name='all_books'),
    path ('item/<slug:slug>/', views.book_details , name='book'),
    path('categories/<slug:slug>/', views.category_list, name='category_list'),


]

eyaya-4- Final project/basket/models.py
from django.db import models

# Create your models here.

eyaya-4- Final project/eyaya3 - Final project/basket/models.py
from django.db import models

# Create your models here.

eyaya-4- Final project/eyaya3 - Final project/store/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse 



# Create your models here.
class Catergory(models.Model):
    name = models.CharField(max_length=255, db_index=True)
    slug = models.SlugField(max_length=255, unique=True)
    class meta:
        verbose_name_plural ='categories'

    def get_absolute_url(self):
        return reverse('store:category_list',args=[self.slug])

    def __str__(self):
        return self.name 
       
class Books(models.Model):
     catergory = models.ForeignKey(Catergory ,related_name='books',on_delete=models.CASCADE)
     created_by = models.ForeignKey(User ,on_delete=models.CASCADE,related_name='product_creator')
     title= models.CharField(max_length=255)
     author= models.CharField(max_length=255)
     isbn= models.CharField(max_length=255)
     copies= models.IntegerField(null=True)
     image = models.ImageField(upload_to='images/')
     slug = models.SlugField(max_length=255)
     in_stock =models.BooleanField(default=True)
     is_active =models.BooleanField(default=True)
     created = models.DateTimeField(auto_now_add= True)
     updated = models.DateTimeField(auto_now_add= True)

     class meta:
        verbose_name_plural ='books'
        ordering = ('-created')

     def get_absolute_url(self):
        return reverse('store:book',args=[str(self.slug)] )
    

     def __str__(self):
        return self.title

eyaya-4- Final project/store/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse 



# Create your models here.
class Catergory(models.Model):
    name = models.CharField(max_length=255, db_index=True)
    slug = models.SlugField(max_length=255, unique=True)
    class meta:
        verbose_name_plural ='categories'

    def get_absolute_url(self):
        return reverse('store:category_list',args=[self.slug])

    def __str__(self):
        return self.name 
       
class Books(models.Model):
     catergory = models.ForeignKey(Catergory ,related_name='books',on_delete=models.CASCADE)
     created_by = models.ForeignKey(User ,on_delete=models.CASCADE,related_name='product_creator')
     title= models.CharField(max_length=255)
     author= models.CharField(max_length=255)
     isbn= models.CharField(max_length=255)
     copies= models.IntegerField(null=True)
     image = models.ImageField(upload_to='images/')
     slug = models.SlugField(max_length=255)
     in_stock =models.BooleanField(default=True)
     is_active =models.BooleanField(default=True)
     created = models.DateTimeField(auto_now_add= True)
     updated = models.DateTimeField(auto_now_add= True)

     class meta:
        verbose_name_plural ='books'
        ordering = ('-created')

     def get_absolute_url(self):
        return reverse('store:book',args=[str(self.slug)] )
    

     def __str__(self):
        return self.title

eyaya-4- Final project/basket/views.py
from django.http import JsonResponse  # Add this import

from django.shortcuts import render
from django.shortcuts import get_object_or_404

from store.models import Books
from . basket import Basket

# Create your views here.
def basket_summary(request):
    basket= Basket(request)
    return render(request, 'store/basket/summary.html',{'basket':basket})

def basket_add(request):
    basket = Basket(request)
    if request.POST.get('action') == 'post':
        book_id = int(request.POST.get('bookid'))
        book_qty = int(request.POST.get('bookqty'))
        book = get_object_or_404(Books, id=book_id)
       
        basket.add(book=book, book_qty=book_qty)  # Fixed variable name here (book_qty)

        basketqty = basket.__len__()
        response = JsonResponse({'book_qty':basketqty})
        return response

eyaya-4- Final project/eyaya3 - Final project/basket/views.py
from django.http import JsonResponse  # Add this import

from django.shortcuts import render
from django.shortcuts import get_object_or_404

from store.models import Books
from . basket import Basket

# Create your views here.
def basket_summary(request):
    basket= Basket(request)
    return render(request, 'store/basket/summary.html',{'basket':basket})

def basket_add(request):
    basket = Basket(request)
    if request.POST.get('action') == 'post':
        book_id = int(request.POST.get('bookid'))
        book_qty = int(request.POST.get('bookqty'))
        book = get_object_or_404(Books, id=book_id)
       
        basket.add(book=book, book_qty=book_qty)  # Fixed variable name here (book_qty)

        basketqty = basket.__len__()
        response = JsonResponse({'book_qty':basketqty})
        return response

eyaya-4- Final project/eyaya3 - Final project/store/views.py
from django.shortcuts import get_object_or_404 ,render

from .models import *

# list of categories
def categories(request):
    return {
        'categories':Catergory.objects.all()
            }

# Create your views here.
def all_books(request):
    my_books = Books.objects.all()
    return render(request,'store/home.html',{'my_books': my_books})

#create single page with book details
def book_details(request, slug):
    book = get_object_or_404 (Books, slug=slug , in_stock=True)
    return render(request,'store/products/detail.html', {'book': book})

# category_list():
def category_list(request, category_slug):
    category = get_object_or_404(Catergory, slug=category_slug)
    my_books = Books.objects.filter(catergory=category)
    return render(request, 'store/products/category.html', {'category': category, 'my_books': my_books})




    

eyaya-4- Final project/store/views.py
from django.shortcuts import get_object_or_404 ,render

from .models import *

# list of categories
def categories(request):
    return {
        'categories':Catergory.objects.all()
            }

# Create your views here.
def all_books(request):
    my_books = Books.objects.all()
    return render(request,'store/home.html',{'my_books': my_books})

#create single page with book details
def book_details(request, slug):
    book = get_object_or_404 (Books, slug=slug , in_stock=True)
    return render(request,'store/products/detail.html', {'book': book})

# category_list():
def category_list(request, category_slug):
    category = get_object_or_404(Catergory, slug=category_slug)
    my_books = Books.objects.filter(catergory=category)
    return render(request, 'store/products/category.html', {'category': category, 'my_books': my_books})




    

eyaya-4- Final project/eyaya3 - Final project/templates/store/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title %}My Library{% endblock %}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-4bw+/aepP/YC94hEpVNVgiZdgIC5+VKNBQNGCHeKRQN+PtmoHDEXuppvnDJzQIu9" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js" integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/js/bootstrap.min.js" integrity="sha384-Rx+T1VzGupg4BHQYs2gCW9It+akI2MM/mndMCy36UVfodzcJcF0GGLxZIzObiEfa" crossorigin="anonymous"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.4/jquery.min.js"></script>
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-md navbar-dark bg-dark">
            <div class="container-fluid">
                <a class="navbar-brand" href="#">Library</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarCollapse">
                    <ul class="navbar-nav me-auto mb-2 mb-md-0">
                        <li class="nav-item">
                            <a class="nav-link active" aria-current="page" href="#">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="#">Link</a>
                        </li>
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">Category</a>
                            <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                                <li><a class="dropdown-item" href="#">All</a></li>
                                {% for c in categories %}
                                <li><a class="dropdown-item" href="{{ categories.get_absolute_url }}">{{ c.name|title }}</a></li>
                                {% endfor %}
                            </ul>
                        </li>
                    </ul>
                    <a type="button" role="button" href="{% url "basket:basket_summary" %}" class="btn btn-outline-secondary">
                        
                        <div id="basket_qty" class="d-inline-flex">
                            {% with total_qty=basket|length %}
                                {% if total_qty > 0 %}
                                    {{ total_qty }}
                                {% else %}
                                    0
                                {% endif %}
                            {% endwith %}
                        </div>
                        
                        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-cart4" viewBox="0 0 16 16">
                            <path d="M0 2.5A.5.5 0 0 1 .5 2H2a.5.5 0 0 1 .485.379L2.89 4H14.5a.5.5 0 0 1 .485.621l-1.5 6A.5.5 0 0 1 13 11H4a.5.5 0 0 1-.485-.379L1.61 3H.5a.5.5 0 0 1-.5-.5zM3.14 5l.5 2H5V5H3.14zM6 5v2h2V5H6zm3 0v2h2V5H9zm3 0v2h1.36l.5-2H12zm1.11 3H12v2h.61l.5-2zM11 8H9v2h2V8zM8 8H6v2h2V8zM5 8H3.89l.5 2H5V8zm0 5a1 1 0 1 0 0 2 1 1 0 0 0 0-2zm-2 1a2 2 0 1 1 4 0 2 2 0 0 1-4 0zm9-1a1 1 0 1 0 0 2 1 1 0 0 0 0-2zm-2 1a2 2 0 1 1 4 0 2 2 0 0 1-4 0z"/>
                        </svg>
                        Basket
                    </a>
                </div>
            </div>
        </nav>
    </header>
    <main>
        <!-- This is where child templates will insert their content -->
        
        {% block content %}{% endblock %}

    </main>
</body>
</html>

eyaya-4- Final project/eyaya3 - Final project/templates/store/basket/summary.html
{% extends "../base.html" %}
{% load static %}

{% block title %}Basket summary{% endblock %}

{% block content %}


<!-- Display the cart quantity -->
<div id="basket_qty" class="d-inline-flex"></div>

<main class="pt-3">

    <div class="container">
        <h1>booking Page</h1>
        {%for item in basket%}
        {%with book=item.book%}
        <main class="pt-5">
            <div class="row g-3">
                <div class="col-md-5 col-lg-5 order-md-first bg-light">
                    <img class="img-fluid mx-auto d-block" width="200px" alt="Responsive image" src="{{ book.image.url }}">
                </div>
                <div class="col-md-7 col-lg-7 ps-md-3 ps-lg-5">
                    <h1 class="mb-0 h4">{{ book.title }}</h1>
                    <p><span class="lead">{{ book.author }}</span>(Author)</p>
                    <p>{{ book.isbn|slice:":355" }}</p>
                    <div class="border">
                        <div class="col border-bottom">
                            <div class="row p-3">
                                <div class="col-6">My books</div>
                                <div class="col-6 text-end"><span class="h4 fw-bold">COPIES {{ basket|length }}</span></div>
                            </div>
                        </div>
                        <!-- ... (previous HTML code) ... -->
<div class="col-6">
    <label for="select">Quantity</label>
    <select id="select" name="quantity"> 
        <option selected>{{item.quantity}}</option>
        <!-- Added name attribute -->
        <option value="1">1</option>
        <option value="2">2</option>
    </select>
</div>
<div class="col-6 text-end">
     <button type="button" id="add-button" value="{{ book.id }}" class="btn btn-secondary">update</button>
     <button type="button" id="delete-button" value="{{ book.id }}" class="btn btn-secondary">delete</button>
</div>
<!-- ... (rest of HTML code) ... -->

                    </div>
                </div>
            </div>
        {%endwith%}    
        {%endfor%}
    </div>
</main>
{% endblock %}

eyaya-4- Final project/eyaya3 - Final project/templates/store/home.html
{% extends "./base.html" %}
{% load static %}

{% block title %}Home{% endblock %}

{% block content %}
    <section class="py-3 text-center container">
        <div class="row py-lg-5">
            <div class="col-lg-6 col-md-8 mx-auto">
                <h1 class="fw-normal text-dark">Search, Read and Review Books</h1>
                <p class="lead text-dark">
                    Something short and leading about the collection below—its contents, the creator, etc.
                    Make it short and sweet, but not too short so folks don’t simply skip over it entirely.
                </p>
                <p>
                    <a href="#" class="btn btn-primary my-2">Create account</a>
                    <a href="#" class="btn btn-secondary my-2">Happy reading</a>
                </p>
            </div>
        </div>
    </section>
    <div class="album py-1 bg-light">
        <div class="container">
            <div class="pb-3 h5"> All Books </div>
            <div class="row row-cols-1 row-cols-sm-2 row-cols-md-5 g-3">
                {% for book in my_books %} 
                <div class="col">
                    <div class="card shadow-sm">
                        <img class="img-fluid" alt="Book Cover" src="{{ book.image.url }}">
                        <div class="card-body">
                            <p class="card-text"> 
                                <a class="text-dark text-decoration-none" href="{{ book.get_absolute_url }}">{{ book.title }}</a>
                            </p>
                            <div class="d-flex justify-content-between align-items-center">
                                <!-- Your content here -->
                                <small class="text-body-secondary">9 mins</small>
                            </div>
                        </div>
                    </div>
                </div>
                {% endfor %}
            </div>
        </div>
    </div>
{% endblock %}

eyaya-4- Final project/eyaya3 - Final project/templates/store/products/category.html
{% extends "../base.html" %}
{% load static %}

{% block title %}
  Home
{% endblock %}

{% block content %}
<main>
  <div class="album py-5 bg-light">
    <div class="container">
      <h2 class="pb-3 h5">{{category.name|title }}</h2>
      <div class="row row-cols-1 row-cols-sm-2 row-cols-md-5 g-3">
        {% for book in my_books %}
        <div class="col">
          <div class="card shadow-sm">
            <img class="img-fluid" alt="Book Cover" src="{{ book.image.url }}">
            <div class="card-body">
              <h5 class="card-title">
                <!-- Inside your template -->
                <a class="text-dark text-decoration-none" href="{% url 'book_details' book.slug %}">{{ book.title }}</a>
              </h5>
              <p class="card-text">{{ book.author }}</p>
              <div class="d-flex justify-content-between align-items-center">
                <small class="text-muted">9 mins</small>
                <span class="badge bg-primary"><a href="{{ book.catergory.get_absolute_url }}">{{ book.catergory.name }}</a></span>
              </div>
            </div>
          </div>
        </div>
        {% endfor %}
      </div>
    </div>
  </div>
</main>
{% endblock %}

eyaya-4- Final project/eyaya3 - Final project/templates/store/products/detail.html
{% extends '../base.html' %}

{% block content %}
    <div class="container">
        <main class="pt-5">
            <div class="row g-3">
                <div class="col-md-5 col-lg-5 order-md-first bg-light">
                    <img class="img-fluid mx-auto d-block" width="200px" alt="Responsive image" src="{{ book.image.url }}">
                </div>
                <div class="col-md-7 col-lg-7 ps-md-3 ps-lg-5">
                    <h1 class="mb-0 h4">{{ book.title }}</h1>
                    <p><span class="lead">{{ book.author }}</span> (Author)</p>
                    <p>{{ book.isbn|slice:":355" }}</p>
                    <div class="border">
                        <div class="col border-bottom">
                            <div class="row p-3">
                                <div class="col-6">Available books</div>
                                <div class="col-6 text-end"><span class="h4 fw-bold">COPIES {{ book.copies }}</span></div>
                            </div>
                        </div>
                        <!-- ... (previous HTML code) ... -->
<div class="col-6">
    <label for="select">Quantity</label>
    <select id="select" name="quantity"> <!-- Added name attribute -->
        <option value="1">1</option>
        <option value="2">2</option>
    </select>
</div>
<div class="col-6 text-end">
    <button type="button" id="add-button" value="{{ book.id }}" class="btn btn-secondary">Add to Basket</button>
</div>
<!-- ... (rest of HTML code) ... -->

                    </div>
                </div>
            </div>
        </main>

    </div>
    <script>
        $(document).on('click', '#add-button', function (e){
            e.preventDefault(); // 'preventDefault' should start with a lowercase 'p'
            $.ajax({
                type: 'POST',
                url: '{% url "basket:basket_add" %}',
                data: {
                    bookid: $('#add-button').val(),
                    bookqty: $('#select option:selected').text(),
                    csrfmiddlewaretoken: "{{ csrf_token }}",
                    action: 'post'
                },
                success: function (json) { // Corrected 'success' spelling
                    // Handle success here
                    //console.log(json)
                    document.getElementById("basket_qty").innerHTML =json.book_qty
                },
                error: function (xhr, errmsg, err) { // Corrected 'error' spelling
                    // Handle error here
                }
            });
        });
    </script>
    {% endblock %}    

eyaya-4- Final project/templates/store/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title %}My Library{% endblock %}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-4bw+/aepP/YC94hEpVNVgiZdgIC5+VKNBQNGCHeKRQN+PtmoHDEXuppvnDJzQIu9" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js" integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/js/bootstrap.min.js" integrity="sha384-Rx+T1VzGupg4BHQYs2gCW9It+akI2MM/mndMCy36UVfodzcJcF0GGLxZIzObiEfa" crossorigin="anonymous"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.4/jquery.min.js"></script>
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-md navbar-dark bg-dark">
            <div class="container-fluid">
                <a class="navbar-brand" href="#">Library</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarCollapse">
                    <ul class="navbar-nav me-auto mb-2 mb-md-0">
                        <li class="nav-item">
                            <a class="nav-link active" aria-current="page" href="#">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="#">Link</a>
                        </li>
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">Category</a>
                            <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                                <li><a class="dropdown-item" href="#">All</a></li>
                                {% for c in categories %}
                                <li><a class="dropdown-item" href="{{ categories.get_absolute_url }}">{{ c.name|title }}</a></li>
                                {% endfor %}
                            </ul>
                        </li>
                    </ul>
                    <a type="button" role="button" href="{% url "basket:basket_summary" %}" class="btn btn-outline-secondary">
                        
                        <div id="basket_qty" class="d-inline-flex">
                            {% with total_qty=basket|length %}
                                {% if total_qty > 0 %}
                                    {{ total_qty }}
                                {% else %}
                                    0
                                {% endif %}
                            {% endwith %}
                        </div>
                        
                        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-cart4" viewBox="0 0 16 16">
                            <path d="M0 2.5A.5.5 0 0 1 .5 2H2a.5.5 0 0 1 .485.379L2.89 4H14.5a.5.5 0 0 1 .485.621l-1.5 6A.5.5 0 0 1 13 11H4a.5.5 0 0 1-.485-.379L1.61 3H.5a.5.5 0 0 1-.5-.5zM3.14 5l.5 2H5V5H3.14zM6 5v2h2V5H6zm3 0v2h2V5H9zm3 0v2h1.36l.5-2H12zm1.11 3H12v2h.61l.5-2zM11 8H9v2h2V8zM8 8H6v2h2V8zM5 8H3.89l.5 2H5V8zm0 5a1 1 0 1 0 0 2 1 1 0 0 0 0-2zm-2 1a2 2 0 1 1 4 0 2 2 0 0 1-4 0zm9-1a1 1 0 1 0 0 2 1 1 0 0 0 0-2zm-2 1a2 2 0 1 1 4 0 2 2 0 0 1-4 0z"/>
                        </svg>
                        Basket
                    </a>
                </div>
            </div>
        </nav>
    </header>
    <main>
        <!-- This is where child templates will insert their content -->
        
        {% block content %}{% endblock %}

    </main>
</body>
</html>

eyaya-4- Final project/templates/store/basket/summary.html
{% extends "../base.html" %}
{% load static %}

{% block title %}Basket summary{% endblock %}

{% block content %}


<!-- Display the cart quantity -->
<div id="basket_qty" class="d-inline-flex"></div>

<main class="pt-3">

    <div class="container">
        <h1>booking Page</h1>
        {%for item in basket%}
        {%with book=item.book%}
        <main class="pt-5">
            <div class="row g-3">
                <div class="col-md-5 col-lg-5 order-md-first bg-light">
                    <img class="img-fluid mx-auto d-block" width="200px" alt="Responsive image" src="{{ book.image.url }}">
                </div>
                <div class="col-md-7 col-lg-7 ps-md-3 ps-lg-5">
                    <h1 class="mb-0 h4">{{ book.title }}</h1>
                    <p><span class="lead">{{ book.author }}</span>(Author)</p>
                    <p>{{ book.isbn|slice:":355" }}</p>
                    <div class="border">
                        <div class="col border-bottom">
                            <div class="row p-3">
                                <div class="col-6">My books</div>
                                <div class="col-6 text-end"><span class="h4 fw-bold">COPIES {{ basket|length }}</span></div>
                            </div>
                        </div>
                        <!-- ... (previous HTML code) ... -->
<div class="col-6">
    <label for="select">Quantity</label>
    <select id="select" name="quantity"> 
        <option selected>{{item.quantity}}</option>
        <!-- Added name attribute -->
        <option value="1">1</option>
        <option value="2">2</option>
    </select>
</div>
<div class="col-6 text-end">
     <button type="button" id="add-button" value="{{ book.id }}" class="btn btn-secondary">update</button>
     <button type="button" id="delete-button" value="{{ book.id }}" class="btn btn-secondary">delete</button>
</div>
<!-- ... (rest of HTML code) ... -->

                    </div>
                </div>
            </div>
        {%endwith%}    
        {%endfor%}
    </div>
</main>
{% endblock %}

eyaya-4- Final project/templates/store/products/detail.html
{% extends '../base.html' %}

{% block content %}
    <div class="container">
        <main class="pt-5">
            <div class="row g-3">
                <div class="col-md-5 col-lg-5 order-md-first bg-light">
                    <img class="img-fluid mx-auto d-block" width="200px" alt="Responsive image" src="{{ book.image.url }}">
                </div>
                <div class="col-md-7 col-lg-7 ps-md-3 ps-lg-5">
                    <h1 class="mb-0 h4">{{ book.title }}</h1>
                    <p><span class="lead">{{ book.author }}</span> (Author)</p>
                    <p>{{ book.isbn|slice:":355" }}</p>
                    <div class="border">
                        <div class="col border-bottom">
                            <div class="row p-3">
                                <div class="col-6">Available books</div>
                                <div class="col-6 text-end"><span class="h4 fw-bold">COPIES {{ book.copies }}</span></div>
                            </div>
                        </div>
                        <!-- ... (previous HTML code) ... -->
<div class="col-6">
    <label for="select">Quantity</label>
    <select id="select" name="quantity"> <!-- Added name attribute -->
        <option value="1">1</option>
        <option value="2">2</option>
    </select>
</div>
<div class="col-6 text-end">
    <button type="button" id="add-button" value="{{ book.id }}" class="btn btn-secondary">Add to Basket</button>
</div>
<!-- ... (rest of HTML code) ... -->

                    </div>
                </div>
            </div>
        </main>

    </div>
    <script>
        $(document).on('click', '#add-button', function (e){
            e.preventDefault(); // 'preventDefault' should start with a lowercase 'p'
            $.ajax({
                type: 'POST',
                url: '{% url "basket:basket_add" %}',
                data: {
                    bookid: $('#add-button').val(),
                    bookqty: $('#select option:selected').text(),
                    csrfmiddlewaretoken: "{{ csrf_token }}",
                    action: 'post'
                },
                success: function (json) { // Corrected 'success' spelling
                    // Handle success here
                    //console.log(json)
                    document.getElementById("basket_qty").innerHTML =json.book_qty
                },
                error: function (xhr, errmsg, err) { // Corrected 'error' spelling
                    // Handle error here
                }
            });
        });
    </script>
    {% endblock %}    